---
title: The Stag Rackenford - Gastropub
timezone: Europe/London
collections:
  events:
    title: Events
    output: true
    permalink: events
  gallery:
    title: Gallery
    output: false
    permalink: gallery
  menus:
    title: Menus
    output: false
    permalink: menus
  posts:
    title: Posts
    output: true
  suppliers:
    title: Suppliers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    layout: event
email: eat@thestagdevon.co.uk
description: A new site
baseurl: 
url: 
twitter_username: tweetsofpayne
telephone: '01884 881755'
email_address: eat@thestagdevon.co.uk
theme: minima
plugins:
- jekyll-feed
sass:
  sass_dir: assets/css/
