---
title: The Stag Rackenford, Devon - English Country Inn
timezone: Europe/London
collections:
  posts:
    title: Events
    output: true
  gallery:
    title: Gallery
    output: false
    permalink: gallery
  menus:
    title: Menus
    output: false
    permalink: menus
    sort_by: position
  stay:
    title: Stay
    output: false
  suppliers:
    title: Suppliers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    date-of-event: ''
- scope:
    path: ''
    type: gallery
  values:
    image: ''
- scope:
    path: ''
    type: suppliers
  values:
    image: ''
    link: ''
- scope:
    path: ''
    type: stay
  values:
    image: ''
    link: ''
description: An English country inn set in the heart of the Devon countryside, just
  off Exmoor National Park, The Stag Rackenford is rumoured to be the oldest pub in
  Devon.
footer_description_text: "Rumoured to be the oldest pub in Devon. TripAdvisor Certificate
  of Excellence 2019. Dog friendly.  \n\n[eat@thestagdevon.co.uk](mailto:eat@thestagdevon.co.uk)
  \ \n\n[01884 881755](tel:01884881755)"
baseurl: 
url: http://www.thestagrackenford.co.uk
twitter_url: 
facebook_url: https://www.facebook.com/The-Stag-inn-Rackenford-101944017885070/
instagram_url: 
tripadvisor_url: https://www.tripadvisor.co.uk/Restaurant_Review-g15561400-d14175231-Reviews-The_Stag-Rackenford_Tiverton_Devon_England.html
telephone: '01884 881755'
email_address: eat@thestagdevon.co.uk
opening_times_text: "We are closed Monday to Thursday and open for pre-booked meals
  as follows:\n(please email for menu)\n\nFriday - Takeaway night only \n\nSaturday
  Dinner - Pre-booked only \n18:00 - 21.30\n\nSunday - Pre-booked only \n12:00 - 16:00
  \ "
reservations_text: "Please call [01884 881755](tel:01884881755) to reserve a table.
  \ \n\n [eat@thestagdevon.co.uk](mailto:eat@thestagdevon.co.uk)"
location_text: |-
  Rackenford, Devon, EX16 8DT.

  Find us just off the A361, the North Devon Link Road.

  [View on Google Maps](https://goo.gl/maps/3fejJabqST38Rr4J8)
theme: minima
plugins:
- jekyll-feed
sass:
  sass_dir: assets/css/
