---
title: The Stag Rackenford - Gastropub
timezone: Europe/London
collections:
  events:
    title: Events
    output: true
    permalink: events
    header: Latest news and events
    text: The colder months are here, which means the aroma of wood fires and mulled
      wine. Our winter programme is packed with entertainment from the very best live
      music in Devon to quiz nights and community orientated events.
  menus:
    title: Menus
    output: true
  posts:
    title: Posts
    output: true
  suppliers:
    title: Suppliers
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: eat@thestagdevon.co.uk
description: A new site
baseurl: 
url: 
twitter_username: tweetsofpayne
github_username: nigelpayne
telephone: '01884 881755'
theme: minima
plugins:
- jekyll-feed
sass:
  sass_dir: assets/css/
