---
title: The Stag Rackenford - Gastropub
timezone: Europe/London
collections:
  posts:
    title: Events
    output: true
  gallery:
    title: Gallery
    output: false
    permalink: gallery
  menus:
    title: Menus
    output: false
    permalink: menus
  suppliers:
    title: Suppliers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: event
- scope:
    path: ''
    type: gallery
  values:
    layout: event
email: eat@thestagdevon.co.uk
description: A new site
footer_description_text: Rumoured to be the oldest pub in Devon. TripAdvisor Certificate
  of Excellence 2019. Dog friendly.
baseurl: 
url: 
twitter_url: 
facebook_url: 
instagram_url: 
tripadvisor_url: 
telephone: '01884 881755'
email_address: eat@thestagdevon.co.uk
opening_times_text: |-
  Wednesday - Saturday
  12:00 - 15:00
  18:00 - 23:00

  Sunday
  12:00 - 16:00
reservations_text: Please call 01884 881755 to reserve a table.
location_text: |-
  Devon, EX16 8DT.
  Find us just off the A361, the North Devon Link Road.
  View on Google Maps
theme: minima
plugins:
- jekyll-feed
sass:
  sass_dir: assets/css/
